[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

[rpc_endpoints]
mainnet = "https://mainnet.infura.io/v3/"
sepolia = "https://sepolia.infura.io/v3/"
polygon = "https://polygon-rpc.com"
localhost = "http://127.0.0.1:8545"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
